config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :champions, only: [:index]
      resources :events, only: [:index]
    end
  end

  namespace :admin do
    resources :applications, only: [:index, :show]
    resources :contributions
    resources :payments, only: [:index, :edit, :update] do
      collection do
        get 'summary'
      end
    end

    get 'home', to: 'pages#home'
    get 'reports', to: 'reports#index'
    get 'over_100', to: 'reports#over_100'
    get 'unpaid_registrations', to: 'reports#unpaid_registrations'
    resources :events do
      resources :resources, except: [:show, :index]
      resources :registration_fees
      resources :attendees do
        resources :guests
      end
      resources :contributions
      resources :promo_cards, except:[:index]
      resources :teams do
        resources :contributions, only: [:edit, :destroy]
      end
      resources :orders
      resources :tickets
      resources :sponsor_levels
      resources :organizers
      get 'concert_summary', to: 'events#concert_summary'
      get 'event_summary', to: 'events#event_summary'
      get 'event_team_summary', to: 'events#event_team_summary'
      get 'event_contact_list', to: 'events#contact_list'
    end
    resources :promotions
    resources :users
    resources :applications, only: [:index, :show, :destroy]
    resources :resources, only: [:index]
    resources :gallery_images
    get 'collect_all', to: 'gallery_images#collect_all'
  end
  resources :contributions, only: [:new, :create]

  resources :events, except: [:new, :create] do
    resources :contributions, except: [:destroy] do
      get 'reciept', to: 'contributions#reciept'
      get 'decline', to: 'contributions#decline'
    end
    resources :comments, only: [:new, :create]
    resources :teams, except: [:index]
    resources :attendees, except: [:index]
    resources :registration_fees
    resources :orders
    resources :sponsorships
    get 'registration-select', to: 'events#registration_select'
    get 'attendees', to: 'events#attendees'
  end

  resources :orders do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'orders#reciept'
    get 'decline', to: 'orders#decline'
  end

  resources :sponsorships do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'sponsorships#reciept'
    get 'decline', to: 'sponsorships#decline'
  end

  resources :contributions, except: [:destroy, :index] do
      resources :payments, only: [:new, :create]
  end

  resources :attendees, except: [:new, :create, :index] do
    # resources :pledge_pages, only: [:edit, :update]
    resources :payments
    get 'reciept', to: 'attendees#reciept'
    get 'decline', to: 'attendees#decline'
    # get 'pledge_page', to: 'pledge_pages#show', as: :pledge_page
    resource :pledge_page, only: [:edit, :update, :show]
    resources :guests, except: [:show]
    resources :contributions, only: [:show, :new, :create, :edit, :update]
    post 'join_team', to: 'attendees#join_team'
  end

  resources :volunteers, only: [:new, :create]

  get 'previous_events', to: 'events#previous_events'
  resources :pledge_page do
    resources :comments, only: [:new, :create]
  end

  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post] #omniauth route
  match '/register', to: 'users#new', via: [:get, :post]

  match '/login', to: 'session#new', via: [:get, :post]
  match '/logout', to: 'session#destroy', via: [:get, :post]
  get '/auth/failure', to: 'session#failure'

  resources :users do  #needed by omniauth-identity
    resources :notifications
    resources :profiles, only: [:new, :create, :edit, :update] do
      member { put :has_nf }
    end
    get 'account_settings', to: 'profiles#show'
  end
  resources :password_resets
  resources :champions do
    resources :contributions
  end

  resources :applications, only: [:new, :create]

  resources :referrals
  get 'top_attendees', to: 'pages#attendees'
  get 'top_teams', to: 'teams#index'
  get 'contribution_select', to: 'contributions#contribution_select'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'nf', to: "pages#nf"

  post 'check_promotion_code', to: 'promotions#check_promotion_code'

  root to: "pages#home"

  if Rails.env.production?
   get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/registration_fee.rb
class RegistrationFee < ApplicationRecord
  belongs_to :event
  
  validates :name, presence: true 
  validates :category, presence: true
  validates :amount, presence: true
  
  scope :is_corporate, -> { where(category: 'Corporate') }
  scope :is_personal, -> { where(category: 'Personal') }
  scope :is_fundraise, -> { where(category: 'Fundraising')}
  
  def name_w_description
    "#{name} $#{amount.round()} - #{description}"
  end
end

app/controllers/admin/registration_fees_controller.rb
class Admin::RegistrationFeesController < ApplicationController
  before_action :set_event, only: [:new, :create, :edit, :update, :destroy]
  before_action :require_user, :require_admin
  
  def new
    @fee = @event.registration_fees.new
  end
  
  def create 
    @fee = @event.registration_fees.create(fee_params)
    
    respond_to do |format|
      if @fee.save
        # format.html redirect_to admin_event_path(@event), :flash => { :success => "Fee has been sucessfully created" }
        format.js
      else
        format.html render :new
      end
    end
  end
  
  def edit
    @fee = RegistrationFee.find(params[:id])
  end
  
  def update
    @fee = RegistrationFee.find(params[:id])
    
    if @fee.update(fee_params)
      redirect_to admin_event_path(@event), :flash => { :success => "Fee Successfully updated"}
    else
      render :edit
    end
  end
  
  def destroy
    
    @fee = RegistrationFee.find(params[:id])
    @fee.destroy
    respond_to do |format|
    format.html {  redirect_to admin_event_path(@event), :flash => { :danger => "Fee successfully deleted" } }
    format.js 
    end
  end
  
  private 
  
    def set_event
      @event = Event.find_by_title(params[:event_id])
    end
    
    def fee_params
      params.require(:registration_fee).permit(:name, :amount, :category, :description, :event_id, :guest_limit)
    end
end

app/controllers/registration_fees_controller.rb
class RegistrationFeesController < ApplicationController
  before_action :set_event 
  def index
  
  end
  
  def create
    @fee = @event.registration_fees.create! registration_fees_parmas
    
    respond_to do |format|
      if @fee.save
        format.html { redirect_to @fee.event, notice: 'Registration Fee was successfully created.' }
        format.js   { }
        format.json { render :show, status: :created, location: @fee }
      else
        format.html { render :new }
        format.json { render json: @fee.errors, status: :unprocessable_entity }
      end
    end
    
   # redirect_to @event
  end
  
  private 
    def set_event
      @event = Event.find_by(params[:event])
    end
    
    def registration_fees_parmas
      params.required(:registration_fee).permit(:name, :amount)
    end
end

app/views/admin/registration_fees/_form.html.erb
<%= form_for([:admin, @event, @fee]) do |f| %>
<% if @fee.errors.any? %>
  <%= render 'shared/errors', errors: @fee.errors %>
<% end %> 

<div class='row'>
  <div class='col-lg-6 offset-md-3'>
    <div class='card card-block'>
    
    <div class='row'>
      <div class='col-12'>
        <%= f.label :name, "Fee Name" %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>
    </div>
    <div>
      <div class='row'>
        <div class='col-12'>
          <%= f.label :category %>
          <%= f.select :category, options_for_select([["Personal", "Personal"], ["Corporate", "Corporate"], ["Fundraising", "Fundraising"]], f.object.category), { :prompt => "Make a Selection" }, class: 'form-control' %>
        </div>
      </div>
    </div>
    <div class='row'>
      <div class='col-12'>
        <%= f.label :amount, "Fee Amount" %>
        <%= f.number_field :amount, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-md-3'>
        <%= f.label :guest_limit, "Guest Limit" %>
        <%= f.number_field :guest_limit, class: 'form-control' %>
      </div>
    </div>
    <div class='row'>
      <div class='col-12'>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control', rows: 5 %>
      </div>
    </div>

    <%= f.submit @fee.new_record? ? "Create Fee" : "Edit Fee", class: 'btn btn-success btn-block my-2' %>       
        <%= link_to "Cancel", admin_event_path(@event), class: 'btn btn-danger btn-block my-2' %>   
    </div>
  </div>
</div>


<% end %> 

app/views/admin/registration_fees/_new.html.erb
<%= form_for( [:admin, @event, RegistrationFee.new ], remote: true) do |f| %>
    <div class='row'>
    <div class='col-md-3'>
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control', id: 'name' %>  
    </div>
    <div class='col-md-3'>
      <%= f.label :category %>
      <%= f.select :category, options_for_select([["Personal", "Personal"], ["Corporate", "Corporate"], ["Fundraising", "Fundraising"]]), { :prompt => "Make a Selection" }, class: 'form-control' %>

    </div>
    <div class='col-md-3'>
      <%= f.label :amount %>
      <%= f.number_field :amount, class: 'form-control', id: 'amount' %>
    </div>    
    <br>
    <div class='col-md-3'>
      <%= f.label :guest_limit, "Guest Limit" %>
      <%= f.number_field :guest_limit, class: 'form-control' %>
    </div>
    <div class='col-md-6'>
      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>
    </div>
    <div class='col-md-3' style='padding-top: 1.80rem;'>
      <%= f.submit 'Submit', class: 'btn btn-primary' %>
    </div> 
    </div>
<% end %>

app/views/admin/registration_fees/_registration_fee.html.erb
<tr id='registration_fee_<%= registration_fee.id %>'>
  <td><%= registration_fee.name %></td>
  <td><%= number_to_currency(registration_fee.amount) %></td>
  <td><%= registration_fee.category %></td>
  <td><%= registration_fee.guest_limit %></td>
  <td><%= link_to 'Edit', edit_admin_event_registration_fee_path(@event, registration_fee) %> | <%= link_to "Delete", admin_event_registration_fee_path(registration_fee.event, registration_fee), method: :delete, data: { confirm: 'Are you sure? (This action can not be undone)' }, remote: true%></td>
</tr>

app/views/admin/registration_fees/create.js.erb
$("#reg_fees").prepend("<%= escape_javascript(render 'registration_fees/registration_fee', registration_fee: @fee ) %>");
$("#amount").val("");
$("#name").val("");

$(".message").html('<%= j render partial: "shared/messages" %>');

app/views/admin/registration_fees/destroy.js.erb
$('#registration_fee_<%= @fee.id %>').remove();

app/views/admin/registration_fees/edit.html.erb
<%= render 'shared/title', title: "Edit Fee: #{@fee.name}", display: 4 %>

<%= render 'form' %>

app/views/admin/registration_fees/new.html.erb
<%= render 'shared/title', title: 'Create Registration Fee', display: 4 %>

<%= render 'form' %>