config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :champions, only: [:index]
      resources :events, only: [:index]
    end
  end

  namespace :admin do
    resources :applications, only: [:index, :show]
    resources :contributions
    resources :payments, only: [:index, :edit, :update] do
      collection do
        get 'summary'
      end
    end

    get 'home', to: 'pages#home'
    get 'reports', to: 'reports#index'
    get 'over_100', to: 'reports#over_100'
    get 'unpaid_registrations', to: 'reports#unpaid_registrations'
    resources :events do
      resources :resources, except: [:show, :index]
      resources :registration_fees
      resources :attendees do
        resources :guests
      end
      resources :contributions
      resources :promo_cards, except:[:index]
      resources :teams do
        resources :contributions, only: [:edit, :destroy]
      end
      resources :orders
      resources :tickets
      resources :sponsor_levels
      resources :organizers
      get 'concert_summary', to: 'events#concert_summary'
      get 'event_summary', to: 'events#event_summary'
      get 'event_team_summary', to: 'events#event_team_summary'
      get 'event_contact_list', to: 'events#contact_list'
    end
    resources :promotions
    resources :users
    resources :applications, only: [:index, :show, :destroy]
    resources :resources, only: [:index]
    resources :gallery_images
    get 'collect_all', to: 'gallery_images#collect_all'
  end
  resources :contributions, only: [:new, :create]

  resources :events, except: [:new, :create] do
    resources :contributions, except: [:destroy] do
      get 'reciept', to: 'contributions#reciept'
      get 'decline', to: 'contributions#decline'
    end
    resources :comments, only: [:new, :create]
    resources :teams, except: [:index]
    resources :attendees, except: [:index]
    resources :registration_fees
    resources :orders
    resources :sponsorships
    get 'registration-select', to: 'events#registration_select'
    get 'attendees', to: 'events#attendees'
  end

  resources :orders do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'orders#reciept'
    get 'decline', to: 'orders#decline'
  end

  resources :sponsorships do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'sponsorships#reciept'
    get 'decline', to: 'sponsorships#decline'
  end

  resources :contributions, except: [:destroy, :index] do
      resources :payments, only: [:new, :create]
  end

  resources :attendees, except: [:new, :create, :index] do
    # resources :pledge_pages, only: [:edit, :update]
    resources :payments
    get 'reciept', to: 'attendees#reciept'
    get 'decline', to: 'attendees#decline'
    # get 'pledge_page', to: 'pledge_pages#show', as: :pledge_page
    resource :pledge_page, only: [:edit, :update, :show]
    resources :guests, except: [:show]
    resources :contributions, only: [:show, :new, :create, :edit, :update]
    post 'join_team', to: 'attendees#join_team'
  end

  resources :volunteers, only: [:new, :create]

  get 'previous_events', to: 'events#previous_events'
  resources :pledge_page do
    resources :comments, only: [:new, :create]
  end

  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post] #omniauth route
  match '/register', to: 'users#new', via: [:get, :post]

  match '/login', to: 'session#new', via: [:get, :post]
  match '/logout', to: 'session#destroy', via: [:get, :post]
  get '/auth/failure', to: 'session#failure'

  resources :users do  #needed by omniauth-identity
    resources :notifications
    resources :profiles, only: [:new, :create, :edit, :update] do
      member { put :has_nf }
    end
    get 'account_settings', to: 'profiles#show'
  end
  resources :password_resets
  resources :champions do
    resources :contributions
  end

  resources :applications, only: [:new, :create]

  resources :referrals
  get 'top_attendees', to: 'pages#attendees'
  get 'top_teams', to: 'teams#index'
  get 'contribution_select', to: 'contributions#contribution_select'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'nf', to: "pages#nf"

  post 'check_promotion_code', to: 'promotions#check_promotion_code'

  root to: "pages#home"

  if Rails.env.production?
   get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :contributions, as: :backable
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :teams, dependent: :destroy
  has_many :attendees
  has_many :guests, through: :attendees
  has_many :registration_fees, dependent: :destroy
  has_many :event_sizes
  has_many :sizes, through: :event_sizes
  has_many :resources, dependent: :destroy
  has_many :champions
  has_many :tickets
  has_many :orders
  has_many :sponsor_levels
  has_many :sponsorships
  has_many :organizers
  has_many :volunteers
  has_one :promo_card

  mount_uploader :event_cover, EventCoverUploader
  mount_uploader :event_card, EventCardUploader
  mount_uploader :organizer_logo, EventCardUploader
  mount_uploader :social_image, EventCardUploader

  validates :name, presence: true, length: {minimun: 5, maximum: 25 }
  validates :goal, presence: true
  validates :desc, presence: true
  validates :event_type, presence: true
  validates :venue_name, presence: true
  validates :street, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :zipcode, presence: true
  validates :event_start_time, presence: true
  validates :event_end_time, presence: true
  validates :registration_date, presence: true
  validates :event_date, presence: true
  validate :event_date_cannot_be_in_the_past
  validate :registration_date_cannot_be_after_event_date

  scope :is_active, -> { where(is_private: false) }
  scope :is_viewable, -> { where("event_date > ? OR event_date IS NULL", Time.zone.now - 1.day).where(is_private: false) }
  scope :is_past, -> { where("event_date < ? OR event_date IS Null", Time.zone.now - 1.day).where(is_private: false) }

  def slug
    if title?
      title.downcase.gsub(" ", "-")
    end
  end

  def to_param
    title
  end

  def event_date_cannot_be_in_the_past
    if event_date.present? && event_date < Date.today
      errors.add(:event_date, "can't be in the past")
    end
  end

  def registration_date_cannot_be_after_event_date
    if event_date.present? && registration_date.present? && registration_date > event_date
      errors.add(:registration_date, "can't be after the start of the event")
    end
  end

  after_find do
    # self.set_active
    update_raised
  end

  def all_attendees
    self.attendees.count + self.guests.count
  end

  def total_raised

    self.contributions.where(paid: true).pluck(:amount).sum + team_total_raised + order_total + sponsorship_total
  end

  def order_total
    amount = 0
    self.orders.where(paid: true).each do |order|
      order.order_items.each do |item|
        amount = amount + item.total
      end
    end

    return amount
  end

  def contributions_count
    self.contributions.count + attendee_contribution_count
  end

  def attendee_contribution_count
    count = 0
    self.attendees.each do |attendee|
      count = count + attendee.contributions.count
    end

    return count
  end

  def team_total_raised

    self.teams.pluck(:raised).sum
  end

  def sponsorship_total
    self.sponsorships.where(paid: true).pluck(:fee).sum
  end

  def percent_raised
    if self.raised > 0
       (self.raised / self.goal) * 100
    end
  end

  after_create do
    self.teams.create( name: "No Team", max_members: 999, event_id: self.id, goal: 10000)
    self.registration_fees.create(name: "Raise $100 (No Payment Now)", category: "Fundraising", amount: 100.00, guest_limit: 0)
    self.registration_fees.create(name: "Adult: 12 and over", category: "Personal", amount: 25.00, guest_limit: 99)
    self.registration_fees.create(name: "Child: 4 to 11", category: "Personal", amount: 12.00, guest_limit: 99)
    self.registration_fees.create(name: "Child: 3 and under", category: "Personal", amount: 6.00, guest_limit: 99)
    self.registration_fees.create(name: "Mile Marker Sponsor", category: "Corporate", amount: 250.00, guest_limit: 0, description: "Employees distribute water and/or name on
mile marker sign, name on local T-shirts and event website")
    self.registration_fees.create(name: "Hometown Sponsor", category: "Corporate", amount: 500.00, guest_limit: 5, description: "Five free walkers from your business,
name on local T-shirt and event website")
    self.registration_fees.create(name: "Silver Sponsor", category: "Corporate", amount: 1000.00, guest_limit: 10, description: "Company name announced at award ceremony, 10 free walkers from your business,
name on the NF banner at the award presentation, name on local T-shirt and event website")
    self.registration_fees.create(name: "Gold Sponsor", category: "Corporate", amount: 2500.00, guest_limit: 25, description: "Framed certificate presented at the award ceremony, 25 free walkers from your business, name on the NF banner at the award Presentation
name on nationwide T-shirt & event websites")
    self.registration_fees.create(name: "Platinum Sponsor", category: "Corporate", amount: 5000.00, guest_limit: 50, description: "Name on the NF Network national website, plaque presented at the award ceremony, 50 free walkers from your business, name on the NF banner at the award presentation, name on nationwide T-shirts and event websites")
    self.update_raised
    self.resources.create(name: "NF Network Brochure", remote_attachment_url: "https://s3.amazonaws.com/nfeventimages/documents/NF+Network+Brochure.pdf")
    self.resources.create(name: "Fundraising Sample Letter", remote_attachment_url: "https://s3.amazonaws.com/nfeventimages/documents/Personal+Story-NF+Hero+Letter.pdf")
    self.resources.create(name: "Donor Form", remote_attachment_url: "https://s3.amazonaws.com/nfeventimages/documents/GS4NF+Donor+Form.pdf")
    self.resources.create(name: "NF Network Pledge Sheet", remote_attachment_url: "https://s3.amazonaws.com/nfeventimages/documents/Great+Steps+Pledge+Sheet.pdf")
    self.resources.create(name: "Fundraising Ideas A-Z", remote_attachment_url: "https://s3.amazonaws.com/nfeventimages/documents/Fundraising+A-Z.pdf")
  end

  after_save do
    self.update_raised
    self.set_title
  end

  def set_title
    self.update_column(:title, "#{Date.today.year}-#{name.downcase.gsub(" ", "-")  }-#{state}")
  end

  def update_raised
      self.update_column(:raised, total_raised)
  end

  # def set_active
  #   if self.registration_date.to_date.past? && self.is_private?
  #       self.update_column(:is_private, false)
  #   elsif self.registration_date.to_date.future? && !self.is_private?
  #       self.update_column(:is_private, true)
  #   end
  # end



end

class NilClass
  def to_date
    Date.today
  end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
  layout "admin"
  before_action :set_event, except: [:index, :new, :create, :concert_summary]
  before_action :require_user, :require_admin


  def index
    @events = Event.all.order(:event_date)
  end

  def show

  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.create(event_params)
    if @event.save
      redirect_to admin_event_path(@event), :flash => { :success => "Event was sucessfully created!"}
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @event.update(event_params)
      redirect_to admin_event_path(@event), :flash => { :success => "Event Successfully Updated!"}
    else
      render :edit
    end
  end

  def destroy

    @event.destroy
    redirect_to admin_home_path, :flash => { :danger => "Event Successfully Deleted!"}
  end

  def concert_summary
    @event = Event.find_by_title(params[:event_id])
    @orders = @event.orders.where(paid: true)
    @contributions = @event.contributions.where(paid: true)

    respond_to do |format|
      format.html
      format.xlsx
    end
  end

  def event_summary
    @event = Event.find_by_title(params[:event_id])
    @attendees = @event.attendees.order(:created_at)
    @contributions = @event.contributions
  end

  def event_team_summary
    @event = Event.find_by_title(params[:event_id])
    @teams = @event.teams.order(:created_at)
    @attendee = @event.attendees
    @contributions = @event.contributions
  end

  def contact_list
    @event = Event.find_by_title(params[:event_id])
    @attendees = @event.attendees.order(:created_at)
  end
  private
    def set_event
      @event = Event.find_by_title(params[:id])
    end
    def event_params
      params.require(:event).permit(:name, :event_cover, :event_card, :event_type, :desc, :teaser, :registration_date, :event_date, :event_start_time, :event_end_time, :goal, :raised, :venue_name, :street, :city, :state, :zipcode, :has_external_registration, :external_url, :has_shirts, :organizer_url, :organizer_logo, :social_image, :social_desc, :is_private, size_ids: [])
    end
end

app/controllers/api/v1/events_controller.rb
class Api::V1::EventsController < ApplicationController

  def index
    events = Event.is_viewable.order(:event_date)

    render json: events
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.order(:event_date)
    # .includes(:contributions)
  end

  # GET /events/1
  # GET /events/1.json
  def show
    @top_fundraisers = @event.attendees.where.not(raised: 0, user_id: 1 ).order(raised: :desc).limit(5)
    @top_teams = @event.teams.where.not(raised: 0, id: @event.teams.first.id).order(raised: :desc).limit(5)
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, :flash[:success] = 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, :flash => { :success => 'Event was successfully updated.' } }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def registration_select
    @event = Event.find_by_title(params[:event_id])
  end

  def attendees
    @event = Event.find_by_title(params[:event_id])
    @attendees = @event.attendees
  end

  def previous_events
    @events = Event.is_past
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find_by_title(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :event_cover, :registration_date, :event_date, :event_start_time, :goal, :raised, :venue_name, :street, :city, :state, :zipcode, :has_shirts, :is_private, size_ids: [])
    end
end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
  
  def states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
  end
  
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/admin/events/_concert.html.erb
<%= render 'shared/title', title: "#{@event.name}", display: 2 %>
<ul class='nav justify-content-center my-4'>
  <li class="nav-item">
    <%= link_to "Orders", admin_event_orders_path(@event), class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "Donations", admin_event_contributions_path(@event), class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "User View", event_path(@event), class: 'nav-link' %>
  </li>
  <li class="nav-item">
    <%= link_to "Edit", edit_admin_event_path(@event), class: 'nav-link btn btn-warning mx-2' %>
  </li>
  <li class='nav-item'>
    <%= link_to "Create Event Summary", admin_event_concert_summary_path(@event, format: :xlsx,), class: 'nav-link btn btn-primary mx-2' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Delete', admin_event_path(@event), method: :delete, data: { confirm: 'Are you sure? (This action can not be undone)' }, class: 'btn btn-danger nav-link mx-2' %>
  </li>
</ul>


<div class='row my-3'>
  <% @event.tickets.each do |ticket| %>
  <div class='col-sm-6 col-lg-4 my-3'>
    <div class='card card-block callout text-center'>
      <h4 class='my-3'>
      <%= ticket.name %>
      <br><br>
      <%= ticket.sold %>
      <br>
      Sold</h4>
    </div>
  </div>
  <% end %>
  <div class='col-sm-8 offset-sm-2 offset-lg-0 col-lg-4 my-3'>
    <div class='card card-block callout text-center' style='min-height: 178px;'>
      <h4 class='my-3'>
      Raised
      <br><br>
      <%= number_to_currency(@event.raised) %>
      </h4>
    </div>
  </div>
</div>



<div class='row'>
  <div class='col-12'>

    <div class='card card-block'>
      <h3 class='card-title'>Tickets Available <%= link_to "Create Ticket", new_admin_event_ticket_path(@event), class: 'btn btn-success float-right' %></h3>

      <table class='table'>
        <thead>
          <th>Ticket Name</th>
          <th>Ticket Price</th>
          <th>Quantity</th>
          <th>Sold</th>
          <th>Available to the Public</th>
          <th>Sold Out</th>
          <th>Actions</th>
        </thead>
        <tbody>
          <%= render @event.tickets %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<%= render 'admin/sponsor_levels/new', event: @event %>

<div class='row'>
  <div class='col-12'>

    <div class='card card-block my-3'>
      <h3 class='card-title'>Sponsor Levels</h3>

      <table class='table'>
        <thead>
          <th>Sponsor Level Name</th>
          <th>Price</th>
          <th>Ticket Type</th>
          <th>Quantity of Tickets</th>
          <th>Desc</th>
          <th>Actions</th>
        </thead>
        <tbody id='sponsor-levels'>
          <%= render @event.sponsor_levels %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/events/edit.html.erb
<%= render 'shared/title', title: "Edit #{ @event.name }" %>
<%= render 'form' %>

app/views/admin/events/index.html.erb
<div class='row my-3'>
  <div class='col-12'>
    <h1>All Events</h1>

<%= link_to "Create Event", new_admin_event_path, class: 'btn btn-success' %>
  </div>
</div>

<div class='row'>
  <% @events.each do |event| %>
    <!--<#% if !event.is_private? %>-->
    <div class='col-md-6 col-sm-12 col-xl-4'>
      <div class='card item-square my-2 shadow'>
        <!--<img class="card-img-top img-fluid" src="https://placehold.it/500x150"> -->
        <% if event.event_cover? %>
          <%= image_tag(event.event_cover.url, class: 'card-img-top img-fluid') %>
        <% else %>
          <%= image_tag "walk-wide.jpg", class: 'card-img-top img-fluid' %>
        <% end %>
        <div class='card-block'>
          <h4 class='card-title'> <%= event.title %></h6>
          <p class='card-text'><%= event.venue_name %> - <%= event.city %>, <%= event.state %><br /> <%= event.event_date.strftime("%A, %B %d %Y") %>
            <br />
            <%= link_to "User View", event_path(event), class: "btn btn-primary mt-3 item-square" %>
            <%= link_to "Manage", admin_event_path(event), class: "btn btn-info mt-3 item-square" %>
            <%= link_to "Edit Event", edit_admin_event_path(event), class: "btn btn-warning mt-3 item-square" %>
          </p>
        </div>
        <div class="card-footer text-muted">
          <div class='row'>
              <!--<div class='col-xs-4'><p class='text-xs-left mb-0'><i class='fa fa-user'></i> <#%= event.attendees.count %></p></div> -->
              <div class='col-6'><p class='text-xs-center mb-0'><i class='fa fa-group'></i> <%= event.teams.count %></p></div>            
              <div class='col-6'><p class='text-right mb-0'><i class='fa fa-usd'></i> <%= number_to_currency(event.raised) %></p></div>
          </div>
        </div>
      </div>
    </div>
    <!--<#% end %>-->
  <% end %>
</div>

app/views/admin/events/new.html.erb
<%= render 'shared/title', title: "Create a New Event" %>
<%= render 'form' %>

app/views/admin/events/show.html.erb
<% if @event.event_type === "Concert" %>
  <%= render 'concert' %>
<% else %>
  <%= render 'shared/title', title: "#{@event.name}", display: 2 %>
    <ul class='nav justify-content-center my-4'>
      <li class="nav-item">
        <%= link_to "Attendees", admin_event_attendees_path(@event), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Teams", admin_event_teams_path(@event), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Donations", admin_event_contributions_path(@event), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "User View", event_path(@event), class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Edit", edit_admin_event_path(@event), class: 'nav-link btn btn-warning mx-2' %>
      </li>
      <li class='nav-item'>
        <%= link_to "Event Organizers", admin_event_organizers_path(@event), class: 'nav-link btn btn-primary mx-2' %>
      </li>
      <li class='nav-item'>
      <div class="dropdown">
        <button class="btn btn-secondary dropdown-toggle nav-link" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Reports
        </button>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
          <%= link_to "Create Event Summary", admin_event_event_summary_path(@event, format: :xlsx,), class: 'dropdown-item' %>
          <%= link_to "Create Team Summary", admin_event_event_team_summary_path(@event, format: :xlsx,), class: 'dropdown-item' %>
          <%= link_to "Create Contact List", admin_event_event_contact_list_path(@event, format: :xlsx,), class: 'dropdown-item' %>
        </div>
      </div>
      </li>
      <!--<li class='nav-item'>-->
      <!--  <#%= link_to "Create Event Summary", admin_event_event_summary_path(@event, format: :xlsx,), class: 'nav-link btn btn-primary mx-2' %>-->
      <!--</li>-->
      <!--<li class='nav-item'>-->
      <!--  <#%= link_to "Create Team Summary", admin_event_event_team_summary_path(@event, format: :xlsx,), class: 'nav-link btn btn-primary mx-2' %>-->
      <!--</li>-->
      <li class="nav-item">
        <%= link_to 'Delete', admin_event_path(@event), method: :delete, data: { confirm: 'Are you sure? (This action can not be undone)' }, class: 'btn btn-danger nav-link mx-2' %>
      </li>
    </ul>
  <div class='row'>
    <div class='col-6'>
      <div class='card card-block'>
        <h3 class='text-center'>Shirt Sizes</h3>
        <%= column_chart @event.attendees.group(:shirt_size).count, backgroundColor: ["pink", "#999"] %>
      </div>
    </div>
    <div class='col-6'>
      <div class='card card-block'>
        <h3 class='text-center'>Registrations By Type</h3>
        <%= pie_chart @event.attendees.group(:fee).count %>
      </div>
    </div>
  </div>

  <div class='row my-3'>
    <div class='col-12 col-xl-6 mb-3'>
      <div class='card card-block'>
        <h3>Registration Fees</h3>
        <%= render 'admin/registration_fees/new', event: @event %>
        <table class='table mt-3'>
          <thead>
            <tr>
              <th>Name</th>
              <th>Amount</th>
              <th>Category</th>
              <th>Guest Limit</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id='reg_fees'>
            <%= render @event.registration_fees %>
          </tbody>
        </table>
      </div>
    </div>
    <div class='col-12 col-xl-6'>
      <div class='card card-block'>
        <h3>Event Resources</h3>
        <%= render 'admin/resources/new', event: @event %>
        <table class='table mt-3'>
          <thead>
            <tr>
              <th>Resource Name</th>
              <th>Resource Attachment</th>
              <th>Created On</th>
              <th>Actions</th>
            </tr>
          </thead>
          <tbody id='resouces'>
            <%= render @event.resources %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class='row my-3'>
    <div class='col-12 col-xl-6 mb-3'>
      <div class='card card-block'>
        <h3 class='card-title'>Event Volunteers</h3>
        <table class='table'>
          <thead>
            <tr>
              <th>ID</th>
              <th>Name</th>
              <th>Email</th>
              <th>Group</th>
              <th>Shirt Size</th>
            </tr>
          </thead>
          <tbody>
            <% @event.volunteers.each do |v| %>
              <tr>
                <td><%= v.id %></td>
                <td><%= v.full_name %></td>
                <td><%= v.email %></td>
                <td><%= v.group_name %></td>
                <td><%= v.shirt_size %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class='row mb-5'>
    <div class='col-12'>
      <div class='card card-block'>
        <h3>Promo Card
          <% if !@event.promo_card.nil? %>
            <%= link_to "Edit", edit_admin_event_promo_card_path(@event, @event.promo_card), class: 'btn btn-warning float-right' %>
          <% else %>
            <%= link_to "Create", new_admin_event_promo_card_path(@event), class: 'btn btn-success float-right' %>
          <% end %>
        </h3>
        <div class='row'>
          <div class='col-xl-10'>
            <% if !@event.promo_card.nil? %>
              <%= render 'promocard' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>