config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :champions, only: [:index]
      resources :events, only: [:index]
    end
  end

  namespace :admin do
    resources :applications, only: [:index, :show]
    resources :contributions
    resources :payments, only: [:index, :edit, :update] do
      collection do
        get 'summary'
      end
    end

    get 'home', to: 'pages#home'
    get 'reports', to: 'reports#index'
    get 'over_100', to: 'reports#over_100'
    get 'unpaid_registrations', to: 'reports#unpaid_registrations'
    resources :events do
      resources :resources, except: [:show, :index]
      resources :registration_fees
      resources :attendees do
        resources :guests
      end
      resources :contributions
      resources :promo_cards, except:[:index]
      resources :teams do
        resources :contributions, only: [:edit, :destroy]
      end
      resources :orders
      resources :tickets
      resources :sponsor_levels
      resources :organizers
      get 'concert_summary', to: 'events#concert_summary'
      get 'event_summary', to: 'events#event_summary'
      get 'event_team_summary', to: 'events#event_team_summary'
      get 'event_contact_list', to: 'events#contact_list'
    end
    resources :promotions
    resources :users
    resources :applications, only: [:index, :show, :destroy]
    resources :resources, only: [:index]
    resources :gallery_images
    get 'collect_all', to: 'gallery_images#collect_all'
  end
  resources :contributions, only: [:new, :create]

  resources :events, except: [:new, :create] do
    resources :contributions, except: [:destroy] do
      get 'reciept', to: 'contributions#reciept'
      get 'decline', to: 'contributions#decline'
    end
    resources :comments, only: [:new, :create]
    resources :teams, except: [:index]
    resources :attendees, except: [:index]
    resources :registration_fees
    resources :orders
    resources :sponsorships
    get 'registration-select', to: 'events#registration_select'
    get 'attendees', to: 'events#attendees'
  end

  resources :orders do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'orders#reciept'
    get 'decline', to: 'orders#decline'
  end

  resources :sponsorships do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'sponsorships#reciept'
    get 'decline', to: 'sponsorships#decline'
  end

  resources :contributions, except: [:destroy, :index] do
      resources :payments, only: [:new, :create]
  end

  resources :attendees, except: [:new, :create, :index] do
    # resources :pledge_pages, only: [:edit, :update]
    resources :payments
    get 'reciept', to: 'attendees#reciept'
    get 'decline', to: 'attendees#decline'
    # get 'pledge_page', to: 'pledge_pages#show', as: :pledge_page
    resource :pledge_page, only: [:edit, :update, :show]
    resources :guests, except: [:show]
    resources :contributions, only: [:show, :new, :create, :edit, :update]
    post 'join_team', to: 'attendees#join_team'
  end

  resources :volunteers, only: [:new, :create]

  get 'previous_events', to: 'events#previous_events'
  resources :pledge_page do
    resources :comments, only: [:new, :create]
  end

  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post] #omniauth route
  match '/register', to: 'users#new', via: [:get, :post]

  match '/login', to: 'session#new', via: [:get, :post]
  match '/logout', to: 'session#destroy', via: [:get, :post]
  get '/auth/failure', to: 'session#failure'

  resources :users do  #needed by omniauth-identity
    resources :notifications
    resources :profiles, only: [:new, :create, :edit, :update] do
      member { put :has_nf }
    end
    get 'account_settings', to: 'profiles#show'
  end
  resources :password_resets
  resources :champions do
    resources :contributions
  end

  resources :applications, only: [:new, :create]

  resources :referrals
  get 'top_attendees', to: 'pages#attendees'
  get 'top_teams', to: 'teams#index'
  get 'contribution_select', to: 'contributions#contribution_select'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'nf', to: "pages#nf"

  post 'check_promotion_code', to: 'promotions#check_promotion_code'

  root to: "pages#home"

  if Rails.env.production?
   get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contribution.rb
class Contribution < ApplicationRecord
  belongs_to :backable, polymorphic: true
  has_many :payments, as: :payable
  belongs_to :user, optional: true
  
  validates :amount, presence: true, numericality: { only_integer: false }
  
  after_create do
    self.backable.update_raised
  end
  
  paginates_per 15
  
  def unpaid_amount
    self.amount
  end
end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < ApplicationController
  layout 'admin'
  before_action :set_event, except: [:new, :create]
  before_action :context, only: [:create]
  before_action :require_user, :require_admin


  def index

    # @search = @event.contributions.ransack(params[:q])
    # @contributions = @search.result(distinct: true).includes(:user).page(params[:page])

    @contributions = Contribution.where(backable: @event).page params[:page]
    @attendees = @event.attendees.joins(:user).merge(User.order(:name))
    respond_to do |format|
      format.js
      format.html
    end
  end

  def new
    @contribution = context.contributions.new
  end


  def create
    # @event = Event.find_by_title(params[:event_id])
    @contribution = context.contributions.create(contribution_params)

    respond_to do |format|
      if @contribution.save
        format.html { redirect_to admin_event_contributions_path(@event), :flash => { :success => "Donation Created" } }
        format.js

      else
        format.js
      end
    end
  end


  private
    def set_event
      @event = Event.find_by_title(params[:event_id])
    end

    def context
      if params[:contribution][:context] == "Attendee"
        Attendee.find(params[:contribution][:backable])
      elsif params[:contribution][:context] == "Event"
        Event.find_by_title(params[:contribution][:event_title])
      end
      # if params[:event_id]
      #   id = params[:event_id]
      #   Event.find_by_title(params[:event_id])
      # elsif params[:attendee_id]
      #   id = params[:attendee_id]
      #   Attendee.find(params[:attendee_id])
      # elsif params[:champion_id]
      #   id = params[:champion_id]
      #   Champion.find(params[:champion_id])
      # else
      #   id = params[:team_id]
      #   Team.find(params[:team_id])
      # end
    end

    def contribution_params
      params.require(:contribution).permit(:amount, :honoree, :category, :paid, :user_id)
    end

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController
  # before_action :require_user, only: [:new, :edit, :destroy]

  def contribution_select
    @events = Event.all


    @pledgepages = PledgePage.last(100)
  end

  def index
    @contributions = Contribution.all
  end

  def new
    @context = context
    @contribution = @context.contributions.new
  end

  def show
    @contribution = Contribution.find(params[:id])
  end

  def create
    @context = context
    @contribution = @context.contributions.new(contribution_params)

    if @contribution.save
      redirect_to  new_contribution_payment_path(@contribution)
      # redirect_to context_url(context, @contribution), flash: { success: 'Your Contribution was Successfully created!' }
    else
      render :new
    end
  end

  def edit
    @contribution = Contribution.find(params[:id])
    @context = @contribution.backable
  end

  def update
    @contribution = Contribution.find(params[:id])
    if @contribution.update_attributes(contribution_params)
      redirect_to new_contribution_payment_path(@contribution), flash: { success: 'Your Contribution was Successfully Updated!' }
    else
      render :edit
    end

  end

  def reciept
    @context = context
    @contribution = Contribution.find(params[:contribution_id])
    @payment = @contribution.payments.where(success: true).first
  end

  def decline
    @context = context
    @contribution = Contribution.find(params[:contribution_id])
    @payment = @contribution.payments.where(success: false).last
  end

  private
    def contribution_params
      params.require(:contribution).permit(:amount, :honoree, :user_id)
    end

    def context
      if params[:event_id]
        id = params[:event_id]
        Event.find_by_title(params[:event_id])
      elsif params[:attendee_id]
        id = params[:attendee_id]
        Attendee.find(params[:attendee_id])
      elsif params[:champion_id]
        id = params[:champion_id]
        Champion.find(params[:champion_id])
       else
        id = params[:team_id]
        Team.find(params[:team_id])
      end
    end

    def context_url(context, contribution)
      if Event === context
        event_contribution_path(context, contribution)
      elsif Attendee === context
        attendee_pledge_page_path(context, context.pledge_page)
      elseif Champion === context
        champion_contribution_path(context, contribution)
      else
        team_path(context)
      end
    end

end

app/views/contributions/_form.html.erb
<%= form_for [@context, @contribution] do |f| %>
  <% if @contribution.errors.any? %>
    <%= render "shared/errors", errors: @contribution.errors %>
  <% end %>


<div class='row'>
  <div class='col-lg-6 offset-lg-3 col-md-8 offset-md-2'>
    <div class='card'>
      <div class='card-block'>
        <h4 class='text-center my-3'>Make a selection or input your own amount</h4>
        <div class='row my-3'>
          <div class='col-12 text-center my-3'>
            <button class='btn btn-primary valueBtn' data-btnvalue='25'>$25</button>
            <button class='btn btn-primary valueBtn' data-btnvalue='50'>$50</button>
            <button class='btn btn-primary valueBtn' data-btnvalue='100'>$100</button>
            <button class='btn btn-primary valueBtn' data-btnvalue='250'>$250</button>
            <button class='btn btn-primary valueBtn' data-btnvalue='500'>$500</button>
            <button class='btn btn-primary' id='btn-other'>Other</button>
          </div>
        </div>

          <%= f.label :amount %>
          <div class="input-group">
            <div class="input-group-addon"><i class='fa fa-usd'></i></div>
            <%= f.number_field :amount, class: "form-control", :value => (number_with_precision(f.object.amount, :precision => 2) || 0)%>
          </div>
          <div class='row mt-3'>
            <div class='col-12'>
              <label class="custom-control custom-checkbox">
                <input type="checkbox" class="custom-control-input" id='in_honor'>
                <span class="custom-control-indicator"></span>
                <span class="custom-control-description">Is this in honor of someone?</span>
              </label>
            </div>
          </div>
          <div id='honoree' style='display: none;'>
            <%= f.label :honoree, "Name of Your Honoree" %>
            <%= f.text_field :honoree, class: "form-control" %>
          </div>

          
          <div class='row'>
            <div class='col-12'>
            <%= f.hidden_field(:user_id, :value => current_user.id) if logged_in? %>
            <%= f.hidden_field(:category, :value => "online") %>
            <%= f.submit class: "btn btn-success btn-block my-3" %>
            <%= link_to "Cancel", :back, class: "btn btn-danger btn-block mb-2 mt-2" %>
            </div>
          </div>
      </div>
    </div>
  </div>
</div>
<% end %>


<script>
  $('.valueBtn').on('click', function(){
    event.preventDefault();
    $('#contribution_amount').val($(this).data("btnvalue"));
  })
  
  $('#btn-other').on('click', function(){
    event.preventDefault();
    $('#contribution_amount').focus();
  })


 $('#in_honor').click(function() {
      if($(this).is(":checked")) {
        console.log("checked");
        $('#honoree').show();
      } else {
        console.log('not checked');
        $('#honoree').hide(); 
      }
  });
  
</script>

app/views/contributions/contribution_select.html.erb
<div class='row' style='background-color: white; margin-top: -46px;'>
  <div class='col-12'>
    <%= render 'shared/title', title: "Where would you like your contribution applied?" %>
  </div>
</div>

<ul class="nav nav-pills nav-fill" id="myTab" role="tablist">
  <li class="nav-item nav-item-custom">
    <a class="nav-link active" data-toggle="tab" href="#events" role="tab" aria-controls="home">Events</a>
  </li>
  <li class="nav-item nav-item-custom">
    <a class="nav-link" data-toggle="tab" href="#pages" role="tab" aria-controls="profile">Fundraising Pages</a>
  </li>
</ul>

<div class='container'>
  <div class='row mt-3'>
    <div class='col-12'>
      <div class="tab-content">
        <div class="tab-pane fade show active" id="events" role="tabpanel">
          <div class='row my-5'>
            <% @events.is_active.each do |event| %>

              <div class='col-lg-4 col-md-6 event-card' onclick='location.href="<%= url_for controller: 'events', action: 'show', id: event.title %>/contributions/new";' style='background-image: url(<%= event.event_card.url %>);'>
                <div class='date-overlay py-3 px-4 text-center'>
                  Contribute</h4>
                </div>
                <div class='title-overlay px-3 py-2'>
                      <%= link_to(event_path(event)) do %>
                  <h4><%= event.city %>, <%= event.state %> - <%= event.name %></h4>
                  <% end %>
                </div>
              </div>
    
            <% end %>
          </div>
        </div>
        <div class="tab-pane fade" id="pages" role="tabpanel">
          <div class='row my-5'>
            <% @pledgepages.each do |pledge| %>
            <div class='col-lg-4 col-md-6 rounded-circle my-3' onclick='location.href="<%= url_for controller: 'pledge_pages', action: 'show', attendee_id: pledge.attendee.id, id: pledge.id %>/contributions/new";' style='background-image: url();'>

              <img src='<% if !pledge.pledge_pic.url.nil? %> <%= pledge.pledge_pic.url %> <% elsif pledge.user.profile_pic? %><%= pledge.user.profile_pic.url %> <% else %> <%= image_url('no_user.png') %> <% end %>' class='img-fluid rounded-circle mx-auto d-block' style='height:250px;'>
              <div class='card card-block my-3'>
              <h4 class='text-center '><%= pledge.user.name.titleize %><br>
                  <%= pledge.event.name + ' - ' + pledge.event.state %>
                  </h4>
                  </div>
              </div>
            <% end %>
</div>
          
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contributions/decline.html.erb
<%= render 'shared/title', title: 'Opps something went wrong...', display: 4 %>

<div class='row'>
  <div class='col-md-8 offset-md-2'>
    <div class='card card-block'>
      <h2>There was an issue processing your credit card.</h2>
      <p>Please attempt the transaction again.</p>
      <%= link_to "Try Again", new_contribution_payment_path(@contribution), class: 'btn btn-success'%>
    </div>
  </div>
</div>

app/views/contributions/edit.html.erb
<%= render 'shared/title', title: "Edit Donation for #{ if @contribution.backable_type == "Attendee" then @contribution.backable.user.name else @contribution.backable.name end }", display: 4 %>


<%= render 'form' %>

app/views/contributions/index.html.erb
<% @contributions.each do |contribution| %>

<h2><%= contribution.id %></h2>
<ul>
  <li>Amount: <%= number_to_currency(contribution.amount) %></li>
  <li>Type: <%= contribution.backable_type %></li>
</ul>

<% end %>

app/views/contributions/new.html.erb
<%= render 'shared/title', title: 'New Donation', display: 4 %>
<%= render 'form' %>

app/views/contributions/reciept.html.erb
<%= render 'shared/title', title: 'Thank you for your payment!' %>

<div class='row my-3'>
  <div class='col-md-8 offset-md-2'>
    <div class='card card-block'>
      <h4 class='mx-2 my-3'>Your confirmation number is <%= @payment.confirmation_number %><button onclick="window.print();" class='btn btn-secondary pull-right'><i class='fa fa-print'></i></button></h4>
      <h4 class='mx-2 my-3'>Your payment was processed for the amount of <%= number_to_currency(@payment.amount) %></h4>
      <h5 class='mx-2 my-3'>You will receive a confirmation email shortly at <%= @contribution.user.nil? ? @payment.email : @contribution.user.email %></h5>
      <div class='row'>
        <div class='col-6 offset-3'>
                <h3 class='text-center mt-4' style="font-family: 'Indie Flower', cursive;">Share With Friends</h3>
    <ul class='nav justify-content-center pr-1 mt-2'>
      <li class='nav-item'><a class='nav-link' href='https://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>' target="_blank"><i class='fa fa-facebook-square fa-3x social-icon' style='color:#3b5998;'></i></a></li>
      <li class='nav-item'><a class='nav-link' href='http://twitter.com/home?status=SHAREMESSAGE' target="_blank" ><i class='fa fa-twitter-square fa-3x social-icon' style='color:#00aced;'></i></a></li>
      <li class='nav-item'><a class='nav-link' href='https://plus.google.com/share?url=<%= request.original_url %>'  target="_blank"><i class='fa fa-google-plus-square fa-3x social-icon' style='color:#dd4b39;'></i></a></li>
      <li class='nav-item'><a class='nav-link' href='https://www.reddit.com/r/Charity/submit?title=Checkout%20the%20event:&url=<%= request.original_url %>' target="_blank"><i class='fa fa-reddit-square fa-3x social-icon' style='color:#FF5700;'></i></a></li>
    </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<div class='row my-3'>
  <div class='col-md-8 offset-md-2'>
    <div class='card card-block'>
      <div class='row'>
        <div class='col-md-4'>
          <% if logged_in? %><%= link_to "View Your Profile", user_path(current_user), class: 'btn btn-block btn-warning' %><% end %>
        </div>
        <div class='col-md-4 offset-md-4'>
          <%= link_to "View Events", events_path, class: 'btn btn-block btn-primary' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contributions/show.html.erb
<div class='row'>
  <div class='col-md-10 offset-md-1 col-lg-6 offset-lg-3'>
    <div class='card mt-3'>
      <div class='card-block'>
        <h2 class='card-title text-center'>Contribution for <% if @contribution.backable_type == "Attendee" then @contribution.backable.user.full_name else @contribution.backable.name end %> </h2>

        <p class='card-text text-center'>
          Amount of Contribution: <%= number_to_currency(@contribution.amount) %>
          <br />
          In Memory/Honor of: <% if @contribution.honoree %> <%= @contribution.honoree %> <% else %> N/A <% end %>
          <div class='row'>
            <div class='col-md-4 my-1'>
              <%= link_to 'Edit', edit_contribution_path(@contribution), class: 'btn btn-warning btn-block' %>
            </div>
            <div class='col-md-4 my-1'>
              <% if !@contribution.paid? %>
                <%= link_to "Submit Payment", new_contribution_payment_path(@contribution), class: 'btn btn-success btn-block' %>
              <% end %>
            </div>
            <div class='col-md-4 my-1'>
              <%= link_to 'Return to Event', event_path(@contribution.backable.id), class: 'btn btn-primary btn-block' %>
            </div>
          </div>
        </p>
      </div>
    </div>
  </div>
</div>