config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :champions, only: [:index]
      resources :events, only: [:index]
    end
  end

  namespace :admin do
    resources :applications, only: [:index, :show]
    resources :contributions
    resources :payments, only: [:index, :edit, :update] do
      collection do
        get 'summary'
      end
    end

    get 'home', to: 'pages#home'
    get 'reports', to: 'reports#index'
    get 'over_100', to: 'reports#over_100'
    get 'unpaid_registrations', to: 'reports#unpaid_registrations'
    resources :events do
      resources :resources, except: [:show, :index]
      resources :registration_fees
      resources :attendees do
        resources :guests
      end
      resources :contributions
      resources :promo_cards, except:[:index]
      resources :teams do
        resources :contributions, only: [:edit, :destroy]
      end
      resources :orders
      resources :tickets
      resources :sponsor_levels
      resources :organizers
      get 'concert_summary', to: 'events#concert_summary'
      get 'event_summary', to: 'events#event_summary'
      get 'event_team_summary', to: 'events#event_team_summary'
      get 'event_contact_list', to: 'events#contact_list'
    end
    resources :promotions
    resources :users
    resources :applications, only: [:index, :show, :destroy]
    resources :resources, only: [:index]
    resources :gallery_images
    get 'collect_all', to: 'gallery_images#collect_all'
  end
  resources :contributions, only: [:new, :create]

  resources :events, except: [:new, :create] do
    resources :contributions, except: [:destroy] do
      get 'reciept', to: 'contributions#reciept'
      get 'decline', to: 'contributions#decline'
    end
    resources :comments, only: [:new, :create]
    resources :teams, except: [:index]
    resources :attendees, except: [:index]
    resources :registration_fees
    resources :orders
    resources :sponsorships
    get 'registration-select', to: 'events#registration_select'
    get 'attendees', to: 'events#attendees'
  end

  resources :orders do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'orders#reciept'
    get 'decline', to: 'orders#decline'
  end

  resources :sponsorships do
    resources :payments, only: [:new, :create]
    get 'reciept', to: 'sponsorships#reciept'
    get 'decline', to: 'sponsorships#decline'
  end

  resources :contributions, except: [:destroy, :index] do
      resources :payments, only: [:new, :create]
  end

  resources :attendees, except: [:new, :create, :index] do
    # resources :pledge_pages, only: [:edit, :update]
    resources :payments
    get 'reciept', to: 'attendees#reciept'
    get 'decline', to: 'attendees#decline'
    # get 'pledge_page', to: 'pledge_pages#show', as: :pledge_page
    resource :pledge_page, only: [:edit, :update, :show]
    resources :guests, except: [:show]
    resources :contributions, only: [:show, :new, :create, :edit, :update]
    post 'join_team', to: 'attendees#join_team'
  end

  resources :volunteers, only: [:new, :create]

  get 'previous_events', to: 'events#previous_events'
  resources :pledge_page do
    resources :comments, only: [:new, :create]
  end

  match '/auth/:provider/callback', to: 'session#create', via: [:get, :post] #omniauth route
  match '/register', to: 'users#new', via: [:get, :post]

  match '/login', to: 'session#new', via: [:get, :post]
  match '/logout', to: 'session#destroy', via: [:get, :post]
  get '/auth/failure', to: 'session#failure'

  resources :users do  #needed by omniauth-identity
    resources :notifications
    resources :profiles, only: [:new, :create, :edit, :update] do
      member { put :has_nf }
    end
    get 'account_settings', to: 'profiles#show'
  end
  resources :password_resets
  resources :champions do
    resources :contributions
  end

  resources :applications, only: [:new, :create]

  resources :referrals
  get 'top_attendees', to: 'pages#attendees'
  get 'top_teams', to: 'teams#index'
  get 'contribution_select', to: 'contributions#contribution_select'
  get 'about', to: 'pages#about'
  get 'privacy', to: 'pages#privacy'
  get 'nf', to: "pages#nf"

  post 'check_promotion_code', to: 'promotions#check_promotion_code'

  root to: "pages#home"

  if Rails.env.production?
   get '404', :to => 'application#page_not_found'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/champion.rb
class Champion < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :event
  has_many :contributions, as: :backable

  mount_uploader :champion_image, ChampionImageUploader

  def update_raised
    return
  end
end

app/controllers/api/v1/champions_controller.rb
class Api::V1::ChampionsController < ApplicationController

  def index
    champions = Champion.order(:created_at)

    render json: champions
  end

end

app/controllers/champions_controller.rb
class ChampionsController < ApplicationController
  before_action :set_champion, only: [:show, :edit, :update, :destroy]
  # before_action :require_user, only: [:new, :create]
  def index
    @champions = Champion.all
  end

  def show

  end

  def new
    @champion = Champion.new
  end

  def create
    @champion = Champion.create(champion_params)

    if @champion.save
      redirect_to champion_path(@champion), :flash => { :success => "Champion Successfully Created" }
    else
      render :new
    end
  end

  def edit

  end

  def update
    if @champion.update(champion_params)
      redirect_to champion_path(@champion), :flash => { :success => "Champion Successfully Updated" }
    else
      render :edit
    end
  end

  def destroy
    @champion.destroy
    redirect_to user_path(current_user), :flash => { :success => "Champion Successfully Deleted"}
  end

  private

  def set_champion
    @champion = Champion.find(params[:id])
  end

  def champion_params
    params.require(:champion).permit(:submitter, :name, :champion_image, :age, :story, :active, :user_id, :event_id)
  end
end

app/views/champions/_form.html.erb
<%= form_for @champion do |f| %>
<% if @champion.errors.any? %>
  <%= render 'shared/errors', errors: @champion.errors %>
<% end %>

<div class='row mb-3'>
  <div class='col-md-8 offset-md-2'>
    <div class='card card-block'>
      <div class='row my-2'>
        <div class='col-12'>
          <%= f.label :submitter, "Nominator's Name" %>
          <%= f.text_field :submitter, class: 'form-control', value: current_user.nil? ? "" : current_user.name.titleize  %>
        </div>
      </div>
      <div class='row my-2'>
        <div class='col-12'>
          <%= f.label :name, "Champion's Name" %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>
      </div>
      <div class='row my-2'>
        <div class='col-4'>
          <%= f.label :champion_image %>
          <%= f.file_field :champion_image, class: 'form-control-file' %>
        </div>
        <div class='col-3'>
          <%= f.label :age, "Age of Your Champion" %>
          <%= f.number_field :age, class: 'form-control' %>
        </div>
        <div class='col-5'>
          <%= f.label :event_id, "Select your NF event:" %>
          <%= f.select :event_id, Event.all.collect { |c| [ c.city + " - " + c.name, c.id ] }, { prompt: "Select One" } , class: 'form-control' %>
        </div>
      </div>
      <div class='row my-2'>
        <div class='col-12'>
          <%= f.label :story, "Your Champion's Story" %>
          <%= f.text_area :story, class: 'form-control', :rows => 15 %>
        </div>
      </div>
      <%= f.hidden_field(:user_id, :value => current_user.id) if logged_in? %>
      <%= f.submit @champion.new_record? ? "Create Champion" : "Update Champion Details", class: 'btn btn-block btn-success mt-3' %>
      <%= link_to "Cancel", :back, class: 'btn btn-block btn-danger mt-3' %>
    </div>
  </div>
</div>

<% end %>

app/views/champions/edit.html.erb
<%= render 'shared/title', title: "Edit Champion Information", display: 4 %>

<%= render 'form' %>

app/views/champions/index.html.erb
<%= render "shared/title", title: 'NF Champs', display: 2 %>
<div class='container'>
  <div class='row m-t-5'>
    <div class='col-md-8'>
      <p class=''>
        Our NF Champs are chosen for their strength, courage, and happiness despite
        difficult circumstances. They are the reason we keep 
        pushing further to find treatments and a cure for 
        neurofibromatosis. View their stories or upload your own 
        and join us in the fight to stay #NFstrong.
      </p>
    </div>
    <div class='col-md-4'>
      <%= link_to "Submit Your Champ", new_champion_path, class: 'btn btn-warning btn-block' %>
  
      <%= link_to "View Events", events_path, class: 'btn btn-primary btn-block' %>
    </div>

  </div>
</div>


<% @champions.each_with_index do |champ, index| %>

<div class='row my-5' <% if index.even? %>style='background-color: #015F88; color: white;' <% end %>>
  <div class='container'>
    <div class='row'>
    <div class='col-md-5 my-5'>
      <h3><%= champ.name.titleize %> - Age: <%= champ.age %></h3>
      <!--<p><#%= champ.story %></p>-->
      <p><%= excerpt(champ.story, 'is', radius: 150) %></p>
      
      <div class='row'>
        <div class='col-4'>
          <%= link_to "Read More", champion_path(champ), class: 'btn btn-block btn-info' %>
        </div>
        <div class='col-8'>
          <%= link_to "Back this Champion", new_champion_contribution_path(champ), class:'btn btn-block btn-success' %>    
        </div>
      </div>
    </div>
    <div class='col-md-7 my-5'>
      <img class='img-fluid rounded d-block mx-auto' src='<%= champ.champion_image %>'>
    </div>
  </div>
  </div>
</div>

<% end %>

app/views/champions/new.html.erb
<%= render 'shared/title', title: "Create New Champion", display: 4 %>

<%= render 'form' %>

app/views/champions/show.html.erb
<% if @champion.event.event_cover? %>
  <div class='row banner-image' style='background-image: url("<%= @champion.event.event_cover.url %>"); margin-top: -46px; background-color: #cccccc; background-size: cover; background-attachment: fixed; min-height:450px;  margin-top: -46px;'>
  </div>
<% else %>
  <div class='row banner-image' style='background-image: url("<%= image_url('walk-wide.jpg') %>"); background-color: #cccccc; background-size: cover; background-attachment: fixed; min-height:450px;  margin-top: -46px;'>
  </div>
<% end %>

<div class='container mb-5'>
  <div class='row'>
    <div class='col-12'>
      <div class='card event-card-shadow primary-pledge-card' style='margin-top: -250px; width: 100%;'>

        <div class='card-block'>
          <div class="row">
            <div class="col-lg-8">
              <div class='row mb-3'>
                <div class='col-lg-5'  style='margin-top: -115px;'>
                  <img class='img-fluid img-thumbnail rounded-circle d-block mx-auto' src='<% if @champion.champion_image? %> <%= @champion.champion_image.url %><% else %><%= image_url('no_user.png') %> <% end %>' style='height: 250px; width:250px'>
                </div>
                <div class='col-lg-7 text-center text-md-center text-lg-left text-sm-center'>
                  <h4><%= @champion.name.titleize %>
                </div>
              </div>
              <h5>
              <%= link_to(event_path(@champion.event)) do %> #NFStrong <%= @champion.event.name %> @ <%= @champion.event.venue_name %><% end %>
              <br />
              <%= @champion.event.event_date.strftime("%A, %B %d %Y") %>
              </h5>

            </div>
            <div class='col-lg-4 mt-4'>
              <h4>Share This Page:</h4>
              <ul class='nav'>
                 <li class='nav-item'><a class='nav-link' id='fbshare'><i class='fa fa-facebook-square fa-3x social-icon' style='color:#3b5998;'></i></a></li>
            <li class='nav-item'><a class='nav-link popup' href="https://twitter.com/share?text=My%20Champion%20helps%20me%20stay%20NFStrong%20will%20support%20finding%20a%20cure&hashtags=NFSTRONG" ><i class='fa fa-twitter-square fa-3x social-icon' style='color:#00aced;'></i></a></li>
            <li class='nav-item'><a class='nav-link' href='https://plus.google.com/share?url=<%= request.original_url %>'  target="_blank"><i class='fa fa-google-plus-square fa-3x social-icon' style='color:#dd4b39;'></i></a></li>
              </ul>
              <hr />
              <h4>Support <%= @champion.name %></h4>
              <%= link_to "View Event", event_path(@champion.event), class: 'btn btn-primary btn-block' %>
              <%= link_to "Donate", new_champion_contribution_path(@champion), class: 'btn btn-success btn-block' %>
            </div>
          </div>
          <hr />
          <div class='row mb-5'>
            <div class='col-12' style='width: 100%'>
              <h4>Champion Story</h4>
              <p>
                <%= @champion.story %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class='row my-3'>
    <div class='col-12'>
      <div class='card event-card-shadow'>
        <div class='card-block'>
          <div class='row'>
            <div class='col-12'>
              <h4>What is NF?</h4>
              <p>
              Neurofibromatosis (NF) is a genetic disorder of the nervous system that causes tumors to form on the nerves anywhere in the body at any time.
              This progressive disorder affects all races, all ethnic groups, and both sexes equally. NF is one of the most common genetic disorders in the United States (one in every 2,500 to 3,000 births).
              The neurofibromatoses effects more than 100,000 Americans; this makes NF more prevalent than Cystic Fibrosis, hereditary muscular dystrophy, Huntington’s disease and tay-sachs combined.
              <br>
              <br>
              NF has three genetically distinct forms: NF-1, NF-2, and Schwannomatosis.
              They are caused by different genes and chromosomes. The effects of NF are unpredictable and have varying manifestations and degrees of severity.
              There is no known cure for any form of NF, although the genes for both NF-1 and NF-2 have been identified.
              <br>
              <br>
              NF is an autosomal dominant genetic condition; it is not contagious. Approximately 50 percent of those affected with neurofibromatosis have a prior family history of NF.
              The other 50 percent of cases are the result of spontaneous genetic mutation.
              </p>
            </div>
          </div>
          <hr />
           <div class='row'>
            <div class='col-12'>
              <h4>About the NF Network</h4>
              The NF Network network provides opportunities for local NF organizations to share experiences.
              The network is a dynamic and growing open space for shared resources, development of new tools,
              and creation of innovative programs.  It brings together groups from around the country to speak as one voice on national issues.
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>


<script>
  $('.popup').click(function(event) {
    var width  = 575,
        height = 400,
        left   = ($(window).width()  - width)  / 2,
        top    = ($(window).height() - height) / 2,
        url    = this.href,
        opts   = 'status=1' +
                 ',width='  + width  +
                 ',height=' + height +
                 ',top='    + top    +
                 ',left='   + left;

    window.open(url, 'twitter', opts);

    return false;
  });

</script>


<script>
  window.fbAsyncInit = function() {
    FB.init({
      appId      : '438500613204488',
      xfbml      : true,
      version    : 'v2.8'
    });
    FB.AppEvents.logPageView();
  };
  (function(d, s, id){
     var js, fjs = d.getElementsByTagName(s)[0];
     if (d.getElementById(id)) {return;}
     js = d.createElement(s); js.id = id;
     js.src = "//connect.facebook.net/en_US/sdk.js";
     fjs.parentNode.insertBefore(js, fjs);
   }(document, 'script', 'facebook-jssdk'));
</script>



<script>
document.getElementById('fbshare').onclick = function() {
  FB.ui({
    method: 'share',
    mobile_iframe: true,
    href: '<%= request.original_url %>',
  }, function(response){});
}
</script>